feat(elasticsearch): add support
Yproximite/manala-recipes pull request #29
Opened 2021-12-21 10:13 UTC by marmorag

OPS-285

Ajout du support d'elasticsearch + kibana

2021-12-21 10:38 UTC, RomulusED69 requested changes

2021-12-21 10:38 UTC, RomulusED69 commented on yprox.app-docker/docker-compose.yaml.tmpl
> +    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
Variable pour la version

2021-12-21 10:38 UTC, RomulusED69 commented on yprox.app-docker/docker-compose.yaml.tmpl
> +    image: docker.elastic.co/kibana/kibana:7.16.2
Idem

2021-12-21 10:38 UTC, RomulusED69 commented on yprox.app-docker/docker-compose.yaml.tmpl
> +      ELASTICSEARCH_URL: http://elasticsearch:9200
Donc on peut pas lancer en // plusieurs projets avec kibana?

2021-12-21 13:39 UTC, marmorag commented on yprox.app-docker/docker-compose.yaml.tmpl
> +    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
tu veux quoi comme version dispo ducoup ?

2021-12-21 14:34 UTC, Kocal reviewed
:eye:

2021-12-21 14:34 UTC, Kocal commented on yprox.app-docker/.manala/Makefile.tmpl
> +	{{- if $has_elastic }} elasticsearch {{ end }}
```suggestion
	{{- if $has_elastic }} elasticsearch{{ end }}
```

2021-12-22 13:41 UTC, RomulusED69 approved these changes

2021-12-22 13:54 UTC, merged